# Generated by Django 3.1.7 on 2021-03-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gitlabsetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_server', models.TextField(blank=True, null=True)),
                ('gitlab_token', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
