# Generated by Django 3.1.7 on 2021-03-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkscanners', '0017_auto_20201006_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='nessus_report_db',
            name='gitlab_ticket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='gitlab_ticket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ov_scan_result_db',
            name='gitlab_ticket',
            field=models.TextField(blank=True, null=True),
        ),
    ]
