# Generated by Django 3.1.7 on 2021-03-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscanners', '0018_auto_20201004_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='acunetix_scan_result_db',
            name='gitlab_ticket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arachni_scan_result_db',
            name='gitlab_ticket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burp_scan_result_db',
            name='gitlab_ticket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netsparker_scan_result_db',
            name='gitlab_ticket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinspect_scan_result_db',
            name='gitlab_ticket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zap_scan_results_db',
            name='gitlab_ticket',
            field=models.TextField(blank=True, null=True),
        ),
    ]
