# Generated by Django 3.1.7 on 2021-03-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_nikto_result_db_nikto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikto_vuln_db',
            name='gitlab_ticket',
            field=models.TextField(blank=True, null=True),
        ),
    ]
